apiVersion: v1
kind: Pod
metadata:
  name: dns-request-pod
  namespace: default
spec:
  containers:
  - name: dns-request-container
    image: wbitt/network-multitool
    command: ["/bin/sh", "-c"]
    args:
    - |
      while true; do
        echo "Requesting example.com using default nameserver...";
        nslookup example.com.;
        sleep 3;
        echo "Requesting socallinuxexpo.org. using 1.2.3.4 nameserver...";
        nslookup socallinuxexpo.org. 1.2.3.4;
        sleep 3;
      done

