apiVersion: v1
kind: Pod
metadata:
  name: stress-hdd-pod
  namespace: default
spec:
  restartPolicy: Never
  containers:
  - name: stress-hdd
    image: alexeiled/stress-ng
    args:
    - --hdd
    - "2"
    - --io
    - "2"
    stdin: true
    tty: true
# Note: the original `kubectl run --rm` flag causes the pod to be deleted automatically
# after it exits. This static manifest does not replicate that behavior.
# Delete the pod manually after use: kubectl delete pod stress-hdd-pod

